{% set version = "4.0.4" %}

package:
  name: procps-ng
  version: {{ version }}

source:
  url: https://gitlab.com/procps-ng/procps/-/archive/v{{ version }}/procps-v{{ version }}.tar.gz
  sha256: 3214fab0f817d169f2c117842ba635bafb1cd6090273e311a8b5c6fc393ddb9d

build:
  number: 0

outputs:
  - name: watch
    build:
      skip: true  # [win]
    script: build-watch.sh

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib('c') }}
        - pkg-config
        - autoconf
        - automake
        - gettext
        - libtool
        - make
        - gettext
        - xz
      host:
        - ncurses
      run:
        - ncurses
      run_constraints:
        - procps-ng <0.0.0a0
    test:
      commands:
        - watch --version

  - name: procps-ng
    build:
      skip: true  # [not linux]
    script: build-all.sh

    requirements:
      build:
        - {{ compiler('c') }}
        - autoconf
        - automake
        - libtool
        - make
        - pkg-config
      host:
        - ncurses
      run:
        - ncurses

    test:
      commands:
        - $PREFIX/bin/ps
        - $PREFIX/bin/w
        - $PREFIX/bin/free

about:
  home: https://gitlab.com/procps-ng/procps
  license: GPL-2.0
  license_family: GPL
  license_file: COPYING
  summary: Command line and full screen utilities for browsing procfs, a "pseudo" file system dynamically generated by the kernel to provide information about the status of entries in its process table.

extra:
  recipe-maintainers:
    - dpryan79
